version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "127.0.0.1:2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "127.0.0.1:9092:9092"
    environment:
      KAFKA_BROKER_ID: 1 
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
  kafka-ui:
    image: provectuslabs/kafka-ui
    ports:
      - "8080:8080"
    environment: 
      DYNAMIC_CONFIG_ENABLED: true
  producer:
    build:
      context: ./producer/
      dockerfile: Dockerfile
    ports:
      - "8085:8080"
    depends_on:
      - kafka
  consumer:
    build:
      context: ./consumer/
      dockerfile: Dockerfile
    ports:
      - "8086:8080"
    depends_on:
      - kafka
